name: Look4Sat CI

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2

      - name: Setup java environment
        uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Run tests, assemble APK and AAB
        id: run_tests_assemble_apk_aab
        run: |
          chmod +x ./gradlew
          ./gradlew test
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Sign release apk
        uses: r0adkll/sign-android-release@v1
        id: sign_release_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Sign release bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_release_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Deploy AAB to Play Store
        uses: r0adkll/upload-google-play@v1
        id: deploy_bundle_to_production
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.rtbishop.look4sat
          track: production
          whatsNewDirectory: fastlane/metadata/android/en-US/changelogs
          releaseFiles: ${{steps.sign_release_bundle.outputs.signedReleaseFile}}

      - name: Upload files to action
        uses: actions/upload-artifact@v2
          with:
            name: Look4Sat_files
            path: |
              ${{steps.sign_release_apk.outputs.signedReleaseFile}}
              ${{steps.sign_release_bundle.outputs.signedReleaseFile}}